### ISSUE TITLE
Tox and Windows on GitHub Actions has inconsistent builds

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/standard-maintenance-scripts#149]
This affects ocds-babel and extension_registry.py.

As an example, this [failing run](https://github.com/open-contracting/extension_registry.py/runs/575634581?check_suite_focus=true) sets [ACTIONS_STEP_DEBUG](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging). Here's a [successful run](https://github.com/open-contracting/extension_registry.py/runs/572647245?check_suite_focus=true).

Potentially related issues:

* https://github.com/tox-dev/tox/issues/257 has old comments in reverse order from https://bitbucket.org/hpk42/tox/issues/257/shell-commands-fail-on-windows-due-to until the new comments
* https://twistedmatrix.com/trac/ticket/8544

```
##[group]Run tox -e clean,py-sphinx15,py-sphinx16,py-sphinx17,py-sphinx18,py-sphinx20,py-sphinx21,py-sphinx22,report
[36;1mtox -e clean,py-sphinx15,py-sphinx16,py-sphinx17,py-sphinx18,py-sphinx20,py-sphinx21,py-sphinx22,report[0m
shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
env:
  pythonLocation: C:\hostedtoolcache\windows\Python\3.6.8\x64
  COVERALLS_REPO_TOKEN: ***
##[endgroup]
##[debug]C:\Program Files\PowerShell\7\pwsh.EXE -command ". 'd:\a\_temp\b5d0553d-7a36-4c21-8e21-4a6b56aa0d9b.ps1'"
GLOB sdist-make: D:\a\extension_registry.py\extension_registry.py\setup.py
___________________________________ summary ___________________________________
  clean: commands succeeded
ERROR:   py-sphinx15: undefined
ERROR:   py-sphinx16: undefined
ERROR:   py-sphinx17: undefined
ERROR:   py-sphinx18: undefined
ERROR:   py-sphinx20: undefined
ERROR:   py-sphinx21: undefined
ERROR:   py-sphinx22: undefined
ERROR:   report: undefined
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\Scripts\tox.exe\__main__.py", line 7, in <module>
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\tox\session\__init__.py", line 44, in cmdline
    main(args)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\tox\session\__init__.py", line 68, in main
    exit_code = session.runcommand()
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\tox\session\__init__.py", line 194, in runcommand
    return self.subcommand_test()
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\tox\session\__init__.py", line 222, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\tox\session\commands\run\sequential.py", line 9, in run_sequential
    if venv.setupenv():
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\tox\venv.py", line 621, in setupenv
    envlog.set_python_info(command_path)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\tox\logs\env.py", line 17, in set_python_info
    answer = get_python_info(str(python_executable))
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\tox\interpreters\via_path.py", line 66, in get_python_info
    universal_newlines=True,
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
##[error]Process completed with exit code 1.
```

**Comment by jpmckinney** [comment]
Removing caching of the tox directory solves it. We might have had the wrong path on Windows, but I don't know what the right one is.
